#!/usr/bin/env php
<?php
/**
 * This executable file runs the websocket server for real-time notifications
 *
 * @package    BZiON
 * @license    https://github.com/allejo/bzion/blob/master/LICENSE.md GNU General Public License Version 3
 */

use Ratchet\Server\IoServer;
use Ratchet\WebSocket\WsServer;
use BZIon\Socket\EventPusher;

set_time_limit(0);

require_once __DIR__.'/../bzion-load.php';
require_once __DIR__.'/AppKernel.php';

$pusher = new EventPusher();

$loop = React\EventLoop\Factory::create();

$pullSocket = new React\Socket\Server($loop);

$pullSocket->on('connection', function ($conn) use($pusher) {
    $conn->on('data', function ($data) use($pusher) {
        $pusher->onServerEvent(json_decode($data));
    });
});

// Bind to 127.0.0.1, so that only the server can send messages to the socket
$pullSocket->listen(WEBSOCKET_PULL_PORT, '127.0.0.1');

$pushSocket = new React\Socket\Server($loop);

$webServer = new IoServer(
    new WsServer(
        $pusher
    ),
    $pushSocket
);

// Binding to 0.0.0.0 means remotes can connect
$pushSocket->listen(WEBSOCKET_PUSH_PORT, '0.0.0.0');

$loop->run();
