$(document).ready(function(){
    $("#news").click(function(){
	$(".team_wrapper").hide();
	$(".home_wrapper").hide();
	$(".profile_wrapper").hide();
	$(".messages_wrapper").hide();
	$(".news_wrapper").show();
    });
    $("#home").click(function(){
	$(".team_wrapper").hide();
	$(".messages_wrapper").hide();
	$(".news_wrapper").hide();
	$(".profile_wrapper").hide();
	$(".home_wrapper").show();
    });
    $("#profile").click(function(){
	$(".team_wrapper").hide();
	$(".news_wrapper").hide();
	$(".home_wrapper").hide();
	$(".messages_wrapper").hide();
	$(".profile_wrapper").show()
    });
    $("#messaging").click(function(){
	$(".team_wrapper").hide();
	$(".news_wrapper").hide();
	$(".home_wrapper").hide();
	$(".profile_wrapper").hide();
	$(".messages_wrapper").show();	
    });    
    $("#teams").click(function(){
	$(".home_wrapper").hide();
	$(".profile_wrapper").hide();
	$(".messages_wrapper").hide();
	$(".news_wrapper").hide();
	$(".team_wrapper").show();
	});
});
